area/ui:
  - pkg/dashboard/ui/**/*

# platforms
platform/kube:
  - pkg/platform/kube/**/*

platform/local:
  - pkg/platform/local/**/*

# triggers
trigger/cron:
  - pkg/processor/trigger/cron/**/*

trigger/http:
  - pkg/processor/trigger/http/**/*

trigger/kafka:
  - pkg/processor/trigger/kafka/**/*

trigger/kickstart:
  - pkg/processor/trigger/kickstart/**/*

trigger/kinesis:
  - pkg/processor/trigger/kinesis/**/*

trigger/mqtt:
  - pkg/processor/trigger/mqtt/**/*

trigger/nats:
  - pkg/processor/trigger/nats/**/*

trigger/partitioned:
  - pkg/processor/trigger/partitioned/**/*

trigger/poller:
  - pkg/processor/trigger/poller/**/*

trigger/pubsub:
  - pkg/processor/trigger/pubsub/**/*

trigger/rabbitmq:
  - pkg/processor/trigger/rabbitmq/**/*

trigger/v3iostream:
  - pkg/processor/trigger/v3iostream/**/*

# runtimes
runtime/python:
  - pkg/processor/**/runtime/python/**/*

runtime/golang:
  - pkg/processor/**/runtime/golang/**/*

runtime/dotnetcore:
  - pkg/processor/**/runtime/dotnetcore/**/*

runtime/java:
  - pkg/processor/**/runtime/java/**/*

runtime/nodejs:
  - pkg/processor/**/runtime/nodejs/**/*

runtime/ruby:
  - pkg/processor/**/runtime/ruby/**/*

runtime/shell:
  - pkg/processor/**/runtime/shell/**/*

# nuctl
nuctl:
  - pkg/nuctl/command/**/*

# releaser
releaser:
  - hack/scripts/releaser/**/*
