#!/bin/bash

# Copyright 2017 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -z "$1" ]; then
    echo "Must specify an external IP address"
    exit 1
fi

# reset any previous cluster
sudo kubeadm reset

# initialize a cluster, adding the public IP address to the certificate
sudo kubeadm init --apiserver-cert-extra-sans=$1

# copy the kube config to home, so we can run kubectl on the machine without specifying --kubeconfig (kubectl
# looks for a config @ ~/.kube/config)
mkdir -p $HOME/.kube
sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

# taint he master node so we can run pods on it (by default we can't)
kubectl taint nodes --all node-role.kubernetes.io/master-

# create a weave CNI
kubectl apply -n kube-system -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

