#!/bin/bash

# Copyright 2017 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mkdir cni_plugins && cd cni_plugins

# get pre-built plugins and untar
wget https://s3.amazonaws.com/iguazio-public/cni-plugins/cni-plugins.tar
tar xzvf cni-plugins.tar
rm cni-plugins.tar

# copy the binaries to the plugins dir
sudo cp * /opt/cni/bin/

# Wait for CNI to complete installation
TIMEOUT=120
while ! test -e /etc/cni/net.d; do
    if [ "$TIMEOUT" == "0" ]; then
        echo "CNI installation didn't complete in 2 mins"
        exit -1
    else
        TIMEOUT=$((TIMEOUT -1))
    fi
    echo "${TIMEOUT} Waiting on folder /etc/cni/net.d to exists"
    sleep 1s
done

# configure to use both weave and the plugin
sudo sh -c 'cat >/etc/cni/net.d/10-mynet.conflist <<-EOF
{
    "cniVersion": "0.3.0",
    "name": "mynet",
      "plugins": [
        {
            "name": "weave",
            "type": "weave-net",
            "hairpinMode": true
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        }
    ]
}
EOF'

# remove prior configuration and restart kube system pods
sudo rm /etc/cni/net.d/10-weave.conf
kubectl delete po --all --namespace=kube-system
