/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/nuclio/nuclio/pkg/platform/kube/apis/nuclio.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNuclioProjects implements NuclioProjectInterface
type FakeNuclioProjects struct {
	Fake *FakeNuclioV1beta1
	ns   string
}

var nuclioprojectsResource = schema.GroupVersionResource{Group: "nuclio.io", Version: "v1beta1", Resource: "nuclioprojects"}

var nuclioprojectsKind = schema.GroupVersionKind{Group: "nuclio.io", Version: "v1beta1", Kind: "NuclioProject"}

// Get takes name of the nuclioProject, and returns the corresponding nuclioProject object, and an error if there is any.
func (c *FakeNuclioProjects) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NuclioProject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nuclioprojectsResource, c.ns, name), &v1beta1.NuclioProject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NuclioProject), err
}

// List takes label and field selectors, and returns the list of NuclioProjects that match those selectors.
func (c *FakeNuclioProjects) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NuclioProjectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nuclioprojectsResource, nuclioprojectsKind, c.ns, opts), &v1beta1.NuclioProjectList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.NuclioProjectList{ListMeta: obj.(*v1beta1.NuclioProjectList).ListMeta}
	for _, item := range obj.(*v1beta1.NuclioProjectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nuclioProjects.
func (c *FakeNuclioProjects) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nuclioprojectsResource, c.ns, opts))

}

// Create takes the representation of a nuclioProject and creates it.  Returns the server's representation of the nuclioProject, and an error, if there is any.
func (c *FakeNuclioProjects) Create(ctx context.Context, nuclioProject *v1beta1.NuclioProject, opts v1.CreateOptions) (result *v1beta1.NuclioProject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nuclioprojectsResource, c.ns, nuclioProject), &v1beta1.NuclioProject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NuclioProject), err
}

// Update takes the representation of a nuclioProject and updates it. Returns the server's representation of the nuclioProject, and an error, if there is any.
func (c *FakeNuclioProjects) Update(ctx context.Context, nuclioProject *v1beta1.NuclioProject, opts v1.UpdateOptions) (result *v1beta1.NuclioProject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nuclioprojectsResource, c.ns, nuclioProject), &v1beta1.NuclioProject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NuclioProject), err
}

// Delete takes name of the nuclioProject and deletes it. Returns an error if one occurs.
func (c *FakeNuclioProjects) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nuclioprojectsResource, c.ns, name), &v1beta1.NuclioProject{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNuclioProjects) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nuclioprojectsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.NuclioProjectList{})
	return err
}

// Patch applies the patch and returns the patched nuclioProject.
func (c *FakeNuclioProjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NuclioProject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nuclioprojectsResource, c.ns, name, pt, data, subresources...), &v1beta1.NuclioProject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NuclioProject), err
}
