/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/nuclio/nuclio/pkg/platform/kube/apis/nuclio.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFunctionEvents implements FunctionEventInterface
type FakeFunctionEvents struct {
	Fake *FakeNuclioV1beta1
	ns   string
}

var functioneventsResource = schema.GroupVersionResource{Group: "nuclio.io", Version: "v1beta1", Resource: "functionevents"}

var functioneventsKind = schema.GroupVersionKind{Group: "nuclio.io", Version: "v1beta1", Kind: "FunctionEvent"}

// Get takes name of the functionEvent, and returns the corresponding functionEvent object, and an error if there is any.
func (c *FakeFunctionEvents) Get(name string, options v1.GetOptions) (result *v1beta1.FunctionEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(functioneventsResource, c.ns, name), &v1beta1.FunctionEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FunctionEvent), err
}

// List takes label and field selectors, and returns the list of FunctionEvents that match those selectors.
func (c *FakeFunctionEvents) List(opts v1.ListOptions) (result *v1beta1.FunctionEventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(functioneventsResource, functioneventsKind, c.ns, opts), &v1beta1.FunctionEventList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.FunctionEventList{}
	for _, item := range obj.(*v1beta1.FunctionEventList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested functionEvents.
func (c *FakeFunctionEvents) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(functioneventsResource, c.ns, opts))

}

// Create takes the representation of a functionEvent and creates it.  Returns the server's representation of the functionEvent, and an error, if there is any.
func (c *FakeFunctionEvents) Create(functionEvent *v1beta1.FunctionEvent) (result *v1beta1.FunctionEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(functioneventsResource, c.ns, functionEvent), &v1beta1.FunctionEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FunctionEvent), err
}

// Update takes the representation of a functionEvent and updates it. Returns the server's representation of the functionEvent, and an error, if there is any.
func (c *FakeFunctionEvents) Update(functionEvent *v1beta1.FunctionEvent) (result *v1beta1.FunctionEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(functioneventsResource, c.ns, functionEvent), &v1beta1.FunctionEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FunctionEvent), err
}

// Delete takes name of the functionEvent and deletes it. Returns an error if one occurs.
func (c *FakeFunctionEvents) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(functioneventsResource, c.ns, name), &v1beta1.FunctionEvent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFunctionEvents) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(functioneventsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.FunctionEventList{})
	return err
}

// Patch applies the patch and returns the patched functionEvent.
func (c *FakeFunctionEvents) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.FunctionEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(functioneventsResource, c.ns, name, data, subresources...), &v1beta1.FunctionEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FunctionEvent), err
}
