/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/nuclio/nuclio/pkg/platform/kube/apis/nuclio.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNuclioFunctions implements NuclioFunctionInterface
type FakeNuclioFunctions struct {
	Fake *FakeNuclioV1beta1
	ns   string
}

var nucliofunctionsResource = schema.GroupVersionResource{Group: "nuclio.io", Version: "v1beta1", Resource: "nucliofunctions"}

var nucliofunctionsKind = schema.GroupVersionKind{Group: "nuclio.io", Version: "v1beta1", Kind: "NuclioFunction"}

// Get takes name of the nuclioFunction, and returns the corresponding nuclioFunction object, and an error if there is any.
func (c *FakeNuclioFunctions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NuclioFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nucliofunctionsResource, c.ns, name), &v1beta1.NuclioFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NuclioFunction), err
}

// List takes label and field selectors, and returns the list of NuclioFunctions that match those selectors.
func (c *FakeNuclioFunctions) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NuclioFunctionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nucliofunctionsResource, nucliofunctionsKind, c.ns, opts), &v1beta1.NuclioFunctionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.NuclioFunctionList{ListMeta: obj.(*v1beta1.NuclioFunctionList).ListMeta}
	for _, item := range obj.(*v1beta1.NuclioFunctionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nuclioFunctions.
func (c *FakeNuclioFunctions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nucliofunctionsResource, c.ns, opts))

}

// Create takes the representation of a nuclioFunction and creates it.  Returns the server's representation of the nuclioFunction, and an error, if there is any.
func (c *FakeNuclioFunctions) Create(ctx context.Context, nuclioFunction *v1beta1.NuclioFunction, opts v1.CreateOptions) (result *v1beta1.NuclioFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nucliofunctionsResource, c.ns, nuclioFunction), &v1beta1.NuclioFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NuclioFunction), err
}

// Update takes the representation of a nuclioFunction and updates it. Returns the server's representation of the nuclioFunction, and an error, if there is any.
func (c *FakeNuclioFunctions) Update(ctx context.Context, nuclioFunction *v1beta1.NuclioFunction, opts v1.UpdateOptions) (result *v1beta1.NuclioFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nucliofunctionsResource, c.ns, nuclioFunction), &v1beta1.NuclioFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NuclioFunction), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNuclioFunctions) UpdateStatus(ctx context.Context, nuclioFunction *v1beta1.NuclioFunction, opts v1.UpdateOptions) (*v1beta1.NuclioFunction, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nucliofunctionsResource, "status", c.ns, nuclioFunction), &v1beta1.NuclioFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NuclioFunction), err
}

// Delete takes name of the nuclioFunction and deletes it. Returns an error if one occurs.
func (c *FakeNuclioFunctions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nucliofunctionsResource, c.ns, name), &v1beta1.NuclioFunction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNuclioFunctions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nucliofunctionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.NuclioFunctionList{})
	return err
}

// Patch applies the patch and returns the patched nuclioFunction.
func (c *FakeNuclioFunctions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NuclioFunction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nucliofunctionsResource, c.ns, name, pt, data, subresources...), &v1beta1.NuclioFunction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NuclioFunction), err
}
