cd ../../pkg/nexus
golangci-lint run ./...
go test -cover ./...
go test -coverprofile=../../profaastinate/tests/coverage.out ./...
cd ../../profaastinate/tests
go tool cover -func coverage.out
go tool cover -func coverage.out | grep total | awk '{print $3}'

