/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// FunctionListerExpansion allows custom methods to be added to
// FunctionLister.
type FunctionListerExpansion interface{}

// FunctionNamespaceListerExpansion allows custom methods to be added to
// FunctionNamespaceLister.
type FunctionNamespaceListerExpansion interface{}

// FunctionEventListerExpansion allows custom methods to be added to
// FunctionEventLister.
type FunctionEventListerExpansion interface{}

// FunctionEventNamespaceListerExpansion allows custom methods to be added to
// FunctionEventNamespaceLister.
type FunctionEventNamespaceListerExpansion interface{}

// ProjectListerExpansion allows custom methods to be added to
// ProjectLister.
type ProjectListerExpansion interface{}

// ProjectNamespaceListerExpansion allows custom methods to be added to
// ProjectNamespaceLister.
type ProjectNamespaceListerExpansion interface{}
