/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// NuclioFunctionListerExpansion allows custom methods to be added to
// NuclioFunctionLister.
type NuclioFunctionListerExpansion interface{}

// NuclioFunctionNamespaceListerExpansion allows custom methods to be added to
// NuclioFunctionNamespaceLister.
type NuclioFunctionNamespaceListerExpansion interface{}

// NuclioFunctionEventListerExpansion allows custom methods to be added to
// NuclioFunctionEventLister.
type NuclioFunctionEventListerExpansion interface{}

// NuclioFunctionEventNamespaceListerExpansion allows custom methods to be added to
// NuclioFunctionEventNamespaceLister.
type NuclioFunctionEventNamespaceListerExpansion interface{}

// NuclioProjectListerExpansion allows custom methods to be added to
// NuclioProjectLister.
type NuclioProjectListerExpansion interface{}

// NuclioProjectNamespaceListerExpansion allows custom methods to be added to
// NuclioProjectNamespaceLister.
type NuclioProjectNamespaceListerExpansion interface{}
