/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1beta1 "github.com/nuclio/nuclio/pkg/platform/kube/apis/nuclio.io/v1beta1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// NuclioFunctionEventInterface is an autogenerated mock type for the NuclioFunctionEventInterface type
type NuclioFunctionEventInterface struct {
	mock.Mock
}

// Create provides a mock function event with given fields: _a0
func (_m *NuclioFunctionEventInterface) Create(_a0 *v1beta1.NuclioFunctionEvent) (*v1beta1.NuclioFunctionEvent, error) {
	ret := _m.Called(_a0)

	var r0 *v1beta1.NuclioFunctionEvent
	if rf, ok := ret.Get(0).(func(*v1beta1.NuclioFunctionEvent) *v1beta1.NuclioFunctionEvent); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.NuclioFunctionEvent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1beta1.NuclioFunctionEvent) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function event with given fields: name, options
func (_m *NuclioFunctionEventInterface) Delete(name string, options *v1.DeleteOptions) error {
	ret := _m.Called(name, options)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.DeleteOptions) error); ok {
		r0 = rf(name, options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCollection provides a mock function event with given fields: options, listOptions
func (_m *NuclioFunctionEventInterface) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	ret := _m.Called(options, listOptions)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.DeleteOptions, v1.ListOptions) error); ok {
		r0 = rf(options, listOptions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function event with given fields: name, options
func (_m *NuclioFunctionEventInterface) Get(name string, options v1.GetOptions) (*v1beta1.NuclioFunctionEvent, error) {
	ret := _m.Called(name, options)

	var r0 *v1beta1.NuclioFunctionEvent
	if rf, ok := ret.Get(0).(func(string, v1.GetOptions) *v1beta1.NuclioFunctionEvent); ok {
		r0 = rf(name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.NuclioFunctionEvent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, v1.GetOptions) error); ok {
		r1 = rf(name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function event with given fields: opts
func (_m *NuclioFunctionEventInterface) List(opts v1.ListOptions) (*v1beta1.NuclioFunctionEventList, error) {
	ret := _m.Called(opts)

	var r0 *v1beta1.NuclioFunctionEventList
	if rf, ok := ret.Get(0).(func(v1.ListOptions) *v1beta1.NuclioFunctionEventList); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.NuclioFunctionEventList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(v1.ListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function event with given fields: name, pt, data, subresources
func (_m *NuclioFunctionEventInterface) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (*v1beta1.NuclioFunctionEvent, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name, pt, data)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1beta1.NuclioFunctionEvent
	if rf, ok := ret.Get(0).(func(string, types.PatchType, []byte, ...string) *v1beta1.NuclioFunctionEvent); ok {
		r0 = rf(name, pt, data, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.NuclioFunctionEvent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, types.PatchType, []byte, ...string) error); ok {
		r1 = rf(name, pt, data, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function event with given fields: _a0
func (_m *NuclioFunctionEventInterface) Update(_a0 *v1beta1.NuclioFunctionEvent) (*v1beta1.NuclioFunctionEvent, error) {
	ret := _m.Called(_a0)

	var r0 *v1beta1.NuclioFunctionEvent
	if rf, ok := ret.Get(0).(func(*v1beta1.NuclioFunctionEvent) *v1beta1.NuclioFunctionEvent); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.NuclioFunctionEvent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1beta1.NuclioFunctionEvent) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function event with given fields: _a0
func (_m *NuclioFunctionEventInterface) UpdateStatus(_a0 *v1beta1.NuclioFunctionEvent) (*v1beta1.NuclioFunctionEvent, error) {
	ret := _m.Called(_a0)

	var r0 *v1beta1.NuclioFunctionEvent
	if rf, ok := ret.Get(0).(func(*v1beta1.NuclioFunctionEvent) *v1beta1.NuclioFunctionEvent); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.NuclioFunctionEvent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1beta1.NuclioFunctionEvent) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function event with given fields: opts
func (_m *NuclioFunctionEventInterface) Watch(opts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(opts)

	var r0 watch.Interface
	if rf, ok := ret.Get(0).(func(v1.ListOptions) watch.Interface); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(v1.ListOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
