#!/bin/sh

# Copyright 2017 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo Shell executed
echo Args: $1 $2 $3
echo Name: $NUCLIO_FUNCTION_NAME
echo Description: $NUCLIO_FUNCTION_DESCRIPTION
echo Event ID: $NUCLIO_EVENT_ID
echo Event source class: $NUCLIO_EVENT_SOURCE_CLASS
echo Event source kind: $NUCLIO_EVENT_SOURCE_KIND

# read from STDIN
read NUCLIO_EVENT_BODY
echo Event body: $NUCLIO_EVENT_BODY
