# Copyright 2017 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nuclio-playground
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nuclio-playground
    spec:
      containers:
      - name: nuclio-playground
        image: nuclio/playground:0.2.3-amd64
        ports:
        - containerPort: 8070
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - name: nuclio-docker-keys
          mountPath: "/etc/nuclio/playground/docker-keys"
          readOnly: true
        env:
        - name: NUCLIO_PLAYGROUND_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: "nuclio-registry"
              key: "registry_url"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: nuclio-docker-keys
        secret:
          secretName: nuclio-docker-keys
---
apiVersion: v1
kind: Service
metadata:
  name: nuclio-playground
spec:
  selector:
    app: nuclio-playground
  type: LoadBalancer
  ports:
  - name: nuclio-playground
    port: 8070
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nuclio-playground-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: nuclio-playground
          servicePort: http
        path: /*
