@startuml
|DeadlineScheduler|
start
while (Should scheduler continue to run?)
    if (Is the queue empty?) then (yes)
        :Sleep for a duration;
        note left
            This is to avoid CPU hogging
            and to allow other processes
            to run.
        end note
    else (no)
        if (Is any item due for execution?) then (yes)
            :Execute item;
            note left
                Removes and executes the item from the queue
                since it has reached its deadline.
                Also adjust number of parallel requests.
            end note
        else (no)
        endif
    endif
endwhile
stop
@enduml
