/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/nuclio/nuclio/pkg/platform/kube/apis/nuclio.io/v1beta1"
	scheme "github.com/nuclio/nuclio/pkg/platform/kube/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NuclioFunctionsGetter has a method to return a NuclioFunctionInterface.
// A group's client should implement this interface.
type NuclioFunctionsGetter interface {
	NuclioFunctions(namespace string) NuclioFunctionInterface
}

// NuclioFunctionInterface has methods to work with NuclioFunction resources.
type NuclioFunctionInterface interface {
	Create(ctx context.Context, nuclioFunction *v1beta1.NuclioFunction, opts v1.CreateOptions) (*v1beta1.NuclioFunction, error)
	Update(ctx context.Context, nuclioFunction *v1beta1.NuclioFunction, opts v1.UpdateOptions) (*v1beta1.NuclioFunction, error)
	UpdateStatus(ctx context.Context, nuclioFunction *v1beta1.NuclioFunction, opts v1.UpdateOptions) (*v1beta1.NuclioFunction, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.NuclioFunction, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.NuclioFunctionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NuclioFunction, err error)
	NuclioFunctionExpansion
}

// nuclioFunctions implements NuclioFunctionInterface
type nuclioFunctions struct {
	client rest.Interface
	ns     string
}

// newNuclioFunctions returns a NuclioFunctions
func newNuclioFunctions(c *NuclioV1beta1Client, namespace string) *nuclioFunctions {
	return &nuclioFunctions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nuclioFunction, and returns the corresponding nuclioFunction object, and an error if there is any.
func (c *nuclioFunctions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NuclioFunction, err error) {
	result = &v1beta1.NuclioFunction{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nucliofunctions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NuclioFunctions that match those selectors.
func (c *nuclioFunctions) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NuclioFunctionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.NuclioFunctionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nucliofunctions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nuclioFunctions.
func (c *nuclioFunctions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nucliofunctions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nuclioFunction and creates it.  Returns the server's representation of the nuclioFunction, and an error, if there is any.
func (c *nuclioFunctions) Create(ctx context.Context, nuclioFunction *v1beta1.NuclioFunction, opts v1.CreateOptions) (result *v1beta1.NuclioFunction, err error) {
	result = &v1beta1.NuclioFunction{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nucliofunctions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nuclioFunction).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nuclioFunction and updates it. Returns the server's representation of the nuclioFunction, and an error, if there is any.
func (c *nuclioFunctions) Update(ctx context.Context, nuclioFunction *v1beta1.NuclioFunction, opts v1.UpdateOptions) (result *v1beta1.NuclioFunction, err error) {
	result = &v1beta1.NuclioFunction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nucliofunctions").
		Name(nuclioFunction.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nuclioFunction).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nuclioFunctions) UpdateStatus(ctx context.Context, nuclioFunction *v1beta1.NuclioFunction, opts v1.UpdateOptions) (result *v1beta1.NuclioFunction, err error) {
	result = &v1beta1.NuclioFunction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nucliofunctions").
		Name(nuclioFunction.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nuclioFunction).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nuclioFunction and deletes it. Returns an error if one occurs.
func (c *nuclioFunctions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nucliofunctions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nuclioFunctions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nucliofunctions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nuclioFunction.
func (c *nuclioFunctions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NuclioFunction, err error) {
	result = &v1beta1.NuclioFunction{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nucliofunctions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
