name: Build and push dashboard image

on:
  workflow_dispatch:
  pull_request:
    branches: [ mpga-development ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nuclio/dashboard
  SET_IMAGE_NAME: nuclio-dashboard-profaastintate

jobs:
  # Install Go 1.21.x
  install-deps:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ 1.21.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go version
          go mod tidy

  # Build and push dashboard image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dashboard image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest-amd64 .

      - name: Tag and push dashboard image
        run: |
            docker tag ${{ env.IMAGE_NAME }}:latest-amd64 ${{ env.REGISTRY }}/${{ env.SET_IMAGE_NAME }}/${{ github.ref_name }}
            docker push ${{ env.REGISTRY }}/${{ env.SET_IMAGE_NAME }}/${{ tag_suffix }}
