name: Validate Profaastinate Nexus

on:
  pull_request:
    branches: [ mpga-development ]

  workflow_dispatch:

jobs:
  install-deps:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ 1.21.x ]  # Add other versions if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go mod tidy

  lint:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - name: Run Profaastinate Lint
        run: golangci-lint run ./pkg/nexus/...

  test:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run Profaastinate Tests
        run: |
          go test -cover ./pkg/nexus/...
          go test -coverprofile=./profaastinate/tests/coverage.out ./pkg/nexus/...
          go tool cover -func ./profaastinate/tests/coverage.out
          go tool cover -func ./profaastinate/tests/coverage.out | grep total | awk '{print $3}'
