# Copyright 2025 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Release

run-name: Releasing ${{ inputs.version }} (${{ github.ref_name }})
env:
  REPO: quay.io
  REPO_NAME: nuclio
  CACHE_REPO: ghcr.io
  CACHE_REPO_NAME: ${{ github.repository_owner }}
  DOCKER_BUILDKIT: 1

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release. If not provided, will be calculated.'
        default: ''
        type: string
      bump_version_mode:
        description: 'Version bump mode'
        default: 'bump-minor'
        type: choice
        options: ['bump-minor', 'bump-major', 'bump-patch']
      target_version:
        description: 'Target version (Optional)'
        required: false
        default: ''
      skip_create_tag_release:
        description: 'Skip creating GitHub tag & release'
        required: false
        default: 'false'
        type: choice
        options: ['true', 'false']
      docker_image_rule:
        description: 'Docker image rule to build and release (space separated)'
        required: false
        default: ''
      branch:
        description: 'The branch to which the release will be merged (default is development).'
        required: false
        default: 'development'
        type: string

jobs:
  prepare-inputs:
    name: Prepare inputs
    runs-on: ubuntu-latest
    outputs:
      prev_version: ${{ steps.resolve.outputs.prev_version }}
      version: ${{ steps.resolve.outputs.version }}
      helm_version: ${{ steps.resolve.outputs.helm_version }}
    steps:
      - uses: actions/checkout@v4
        with:

          # Fetch all history for all tags and branches
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run Go script
        run: |
          make get-release-info BUMP_VERSION_MODE=${{ inputs.bump_version_mode }} TARGET_VERSION=${{ inputs.target_version }}

      - name: Resolve inputs
        id: resolve
        run: |
          CURRENT_VERSION_INPUT=$(make get-current-version)
          TARGET_VERSION_INPUT=$(make get-target-version)
          HELM_VERSION_INPUT=$(make get-helm-target-version)
          
          echo "CURRENT_VERSION_INPUT=${CURRENT_VERSION_INPUT}"
          echo "TARGET_VERSION_INPUT=${TARGET_VERSION_INPUT}"
          echo "HELM_VERSION_INPUT=${HELM_VERSION_INPUT}"

          echo "prev_version=${CURRENT_VERSION_INPUT}" >> $GITHUB_OUTPUT
          echo "version=${TARGET_VERSION_INPUT}" >> $GITHUB_OUTPUT
          echo "helm_version=${HELM_VERSION_INPUT}" >> $GITHUB_OUTPUT

  create-release:
    name: Update release notes and create release
    runs-on: ubuntu-latest
    if: github.event.inputs.skip_create_tag_release != 'true'
    needs: [ prepare-inputs ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/install.sh | sh
          gh --version

      - name: Generate Structured Release Notes
        run: |
          LATEST_TAG=${{ needs.prepare-inputs.outputs.prev_version }}
          RELEASE_NOTES=$(git log $LATEST_TAG..${GITHUB_SHA} --pretty=format:'- [%h] %s by @%an in #%d' --abbrev-commit | sed 's/(.*)//')
          echo "$RELEASE_NOTES" > release_notes.md

      - name: Create Release
        run: |
          gh release create v${{ needs.prepare-inputs.outputs.version }} \
            --title "Release v${{ needs.prepare-inputs.outputs.version }}" \
            --notes-file release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  helm-bump-create-pr:
    runs-on: ubuntu-latest
    needs: [ prepare-inputs ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Define branch name
        run: |
          echo "HELM_BRANCH_NAME=update-helm-charts-${{ needs.prepare-inputs.outputs.helm_version }}" >> $GITHUB_ENV

      - name: Checkout or create branch
        run: |
          git fetch origin $HELM_BRANCH_NAME || true
          if git rev-parse --verify origin/$HELM_BRANCH_NAME >/dev/null 2>&1; then
            git checkout $HELM_BRANCH_NAME
            git pull origin $HELM_BRANCH_NAME
          else
            git checkout -b $HELM_BRANCH_NAME
          fi

      - name: Make changes to files
        run: |
          make bump-helm-charts BUMP_VERSION_MODE=${{ inputs.bump_version_mode }} TARGET_VERSION=${{ inputs.target_version }}

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Bump Helm charts to ${{ needs.prepare-inputs.outputs.version }}" || echo "No changes to commit"
          git push --set-upstream origin $HELM_BRANCH_NAME
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[Helm] Bump Helm charts"
          body: "This PR contains changes automatically generated by the CI `release` pipeline."
          team-reviewers: |
            maintainers
          repository: ${{ github.repository }}
          head: ${{ env.HELM_BRANCH_NAME }}
          base: ${{ github.event.inputs.branch }}


