# Copyright 2025 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Release

run-name: Releasing ${{ inputs.version }} (${{ github.ref_name }})

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release. if not provided, will be calculated from the current version and bump_version_mode'
        default: ''
        type: string
      bump_version_mode:
        description: 'The version bump mode. Whether to bump rc version or set stable version'
        default: 'bump-minor'
        type: choice
        options: [ 'bump-minor', 'bump-major', 'bump-patch']
      skip_images:
        description: 'Comma separated list of images to skip building, example with all possible images: mlrun,mlrun-gpu,ui,api,base,jupyter,test'
        required: false
        default: ''
      skip_create_tag_release:
        description: 'Whether to skip creating tag & release in Github (Auto skip for feature branch)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'

jobs:
  prepare-inputs:
    name: Prepare inputs
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.resolve.outputs.version }}
      previous_version: ${{ steps.resolve.outputs.previous_version }}
    steps:
      - uses: actions/checkout@v4
        with:

          # Fetch all history for all tags and branches
          fetch-depth: 0
      - name: Resolve inputs
        id: resolve
        run: |

          # map the input to the actual mode
          declare -A bump_version_mode=(["bump-rc"]="rc" ["stable"]="rc-grad")
          NEXT_VERSION_MODE=${bump_version_mode[$BUMP_VERSION_MODE_INPUT]}
          version=$(python ./automation/version/version_file.py next-version --mode $NEXT_VERSION_MODE)
          echo "Calculated version: $version"
          if [[ -n "$VERSION_INPUT" ]]; then \
            version=$VERSION_INPUT; \
            echo "Using version from input: $version"; \
          fi

          echo "version=$version" >> $GITHUB_OUTPUT
          echo "previous_version=$(python ./automation/version/version_file.py current-version)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        env:
          UI_REF_INPUT: ${{ github.event.inputs.ui_ref }}
          BUMP_VERSION_MODE_INPUT: ${{ github.event.inputs.bump_version_mode }}
          VERSION_INPUT: ${{ github.event.inputs.version }}

  trigger-and-wait-for-mlrun-image-building:
    name: Trigger build workflow in mlrun/mlrun and wait to finish
    needs: prepare-inputs
    uses: ./.github/workflows/build-internal.yaml
    with:
      docker_registries: "ghcr.io/,quay.io/,registry.hub.docker.com/"
      version: ${{ needs.prepare-inputs.outputs.version }}
      skip_images: ${{ github.event.inputs.skip_images }}
    secrets: inherit
  create-releases:
    name: Create release & tag v${{ needs.prepare-inputs.outputs.version }}
    runs-on: ubuntu-latest
    if: needs.prepare-inputs.outputs.is_feature_branch == 'false'
    needs: [ prepare-inputs, publish-to-pypi ]
    steps:
      - uses: ncipollo/release-action@v1
        if: github.event.inputs.skip_create_tag_release != 'true'
        with:
          tag: v${{ needs.prepare-inputs.outputs.version }}
          commit: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ needs.prepare-inputs.outputs.is_stable_version == 'false' }}
      - uses: ncipollo/release-action@v1
        if: github.event.inputs.skip_create_tag_release != 'true'
        with:
          repo: ui
          tag: v${{ needs.prepare-inputs.outputs.version }}
          commit: ${{ github.ref_name }}
          token: ${{ secrets.RELEASE_GITHUB_ACCESS_TOKEN }}
          # experienced 500 errors when trying to create release notes for ui repo with `prerelease flag`
          # prerelease: ${{ needs.prepare-inputs.outputs.prerelease }}

  create-tag:
    name: Create tag v${{ needs.prepare-inputs.outputs.version }}
    runs-on: ubuntu-latest

    # run this specific job for feature branch only as we wont have a github release for it
    # the tag would be useful to track feature branch released versions
    if: needs.prepare-inputs.outputs.is_feature_branch == 'true'
    needs: [ prepare-inputs, trigger-and-wait-for-mlrun-image-building ]
    steps:
      - name: Create feature branch tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ needs.prepare-inputs.outputs.version }}',
              sha: context.sha
            })

  update-release-notes:
    name: Update release notes
    runs-on: ubuntu-latest
    if: github.event.inputs.skip_create_tag_release != 'true'
    # runs lastly to avoid conflicts with other release-related jobs
    needs: [ prepare-inputs, update-tutorials, update-demos ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r automation/requirements.txt
      - name: Generate release notes
        id: release-notes
        run: |
          make release-notes
        env:
          MLRUN_SKIP_CLONE: true
          MLRUN_RELEASE_BRANCH: ${{ github.ref_name }}
          MLRUN_RELEASE_NOTES_OUTPUT_FILE: release_notes.md
          MLRUN_RAISE_ON_ERROR: false
          MLRUN_OLD_VERSION: "v${{ needs.prepare-inputs.outputs.previous_version }}"
          MLRUN_VERSION: "v${{ needs.prepare-inputs.outputs.version }}"

      - name: resolve release notes
        id: resolve-release-notes
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat release_notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.prepare-inputs.outputs.version }}
          body: ${{ steps.resolve-release-notes.outputs.body }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          prerelease: ${{ needs.prepare-inputs.outputs.is_stable_version == 'false' }}