# Copyright 2025 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Release

run-name: Releasing ${{ inputs.target_version }} ${{ github.event.inputs.branch }}
env:
  REPO: quay.io
  REPO_NAME: nuclio
  CACHE_REPO: ghcr.io
  CACHE_REPO_NAME: ${{ github.repository_owner }}
  DOCKER_BUILDKIT: 1

permissions:
  contents: write
  packages: write
  pull-requests: write

on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:
      target_version:
        description: 'The version to release. If not provided, will be calculated.'
        default: ''
        type: string
      bump_version_mode:
        description: 'Version bump mode'
        default: 'bump-minor'
        type: choice
        options: ['bump-minor', 'bump-major', 'bump-patch']
      helm_chart_target_version:
        description: 'Helm chart target version (Optional)'
        required: false
        default: ''
      skip_create_tag_release:
        description: 'Skip creating GitHub tag & release'
        required: false
        default: 'false'
        type: choice
        options: ['true', 'false']
      skip_bump_helm_charts:
        description: 'Skip bumping helm charts'
        required: false
        default: 'false'
        type: choice
        options: [ 'true', 'false' ]
      bump_helm_charts_only:
        description: 'Bump helm charts only'
        required: false
        default: 'false'
        type: choice
        options: [ 'true', 'false' ]
      docker_image_rule:
        description: 'Docker image rule to build and release (space separated)'
        required: false
        default: ''
      branch:
        description: 'The branch from which release will be created and to which the release will be merged (default is development).'
        required: false
        default: 'development'
        type: string

jobs:
  prepare-inputs:
    name: Prepare inputs
    runs-on: ubuntu-latest
    outputs:
      prev_version: ${{ steps.resolve.outputs.prev_version }}
      version: ${{ steps.resolve.outputs.version }}
      helm_version: ${{ steps.resolve.outputs.helm_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          # Fetch all history for all tags and branches
          fetch-depth: 0

      - name: Set up Go
        if: github.event_name == 'workflow_dispatch'
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: Get release info
        if: github.event_name == 'workflow_dispatch'
        run: |
          make get-release-info
        env:
          BUMP_VERSION_MODE: ${{ inputs.bump_version_mode }}
          TARGET_VERSION: ${{ inputs.target_version }}
          HELM_TARGET_VERSION: ${{ inputs.helm_chart_target_version }}

      - name: Resolve version inputs
        id: resolve
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            CURRENT_VERSION_INPUT=$(make get-current-version)
            TARGET_VERSION_INPUT=$(make get-target-version)
            HELM_VERSION_INPUT=$(make get-helm-target-version)

            echo "CURRENT_VERSION_INPUT=${CURRENT_VERSION_INPUT}"
            echo "TARGET_VERSION_INPUT=${TARGET_VERSION_INPUT}"
            echo "HELM_VERSION_INPUT=${HELM_VERSION_INPUT}"

            echo "prev_version=${CURRENT_VERSION_INPUT}" >> $GITHUB_OUTPUT
            echo "version=${TARGET_VERSION_INPUT}" >> $GITHUB_OUTPUT
            echo "helm_version=${HELM_VERSION_INPUT}" >> $GITHUB_OUTPUT
          else
            echo "prev_version=" >> $GITHUB_OUTPUT
            echo "version=unstable" >> $GITHUB_OUTPUT
            echo "helm_version=" >> $GITHUB_OUTPUT
          fi

  release:
    name: Generate Changelog & Create Release
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.skip_create_tag_release != 'true'
    runs-on: ubuntu-latest
    needs: [ prepare-inputs ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Generate Changelog with git-cliff
        uses: orhun/git-cliff-action@4a4a951bc43fafe41cd2348d181853f52356bee7 # 4.4.2
        id: git-cliff
        with:
          config: cliff.toml
          args: ${{ needs.prepare-inputs.outputs.prev_version }}..HEAD --tag ${{ needs.prepare-inputs.outputs.version }}
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the Changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Create GitHub Release
        run: |
          gh release create ${{ needs.prepare-inputs.outputs.version }} \
            --title "${{ needs.prepare-inputs.outputs.version }}" \
            --notes-file CHANGELOG.md \
            --target ${{ github.event.inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump-helm-charts:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.skip_bump_helm_charts != 'true'
    needs: [ prepare-inputs ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Bump chart versions
        run: |
          make bump-helm-charts
        env:
          BUMP_VERSION_MODE: ${{ inputs.bump_version_mode }}
          TARGET_VERSION: ${{ inputs.target_version }}
          HELM_TARGET_VERSION: ${{ inputs.helm_chart_target_version }}

      - name: Create pull request with bumped charts
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[Chart] Bump to ${{ needs.prepare-inputs.outputs.version }}"
          branch: chart-bump-${{ needs.prepare-inputs.outputs.version }}
          title: "[Chart] Bump to ${{ needs.prepare-inputs.outputs.version }}"
          base: ${{ github.event.inputs.branch }}
          body: "This PR was automatically created by the release workflow to bump Helm chart version to ${{ needs.prepare-inputs.outputs.version }}."
          delete-branch: true

  image_matrix_prep:
    name: Prepare image list
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - name: define targets
        id: set-matrix
        run: |

          # if custom image is given, use it
          if [[ -n "${{ github.event.inputs.docker_image_rule }}" ]]; then \
            export DOCKER_IMAGES_RULES="${{ github.event.inputs.docker_image_rule }}"; \
          fi;

          docker_image_rules_json=$(make print-docker-image-rules-json)

          # if "handler-builder-golang-onbuild" is in the matrix
          # then ensure "handler-builder-golang-onbuild-alpine" is there too.
          docker_image_rules_json=$(echo $docker_image_rules_json | \
            jq -c 'select(.[].image_rule=="handler-builder-golang-onbuild") += [{"image_rule":"handler-builder-golang-onbuild-alpine"}]')

          echo $docker_image_rules_json
          echo "matrix=$(echo $docker_image_rules_json | jq -c '[.[].image_rule]')" >> $GITHUB_OUTPUT

  release-images:
    if: (github.repository == 'nuclio/nuclio' || github.event_name == 'workflow_dispatch')  && github.event.inputs.bump_helm_charts_only != 'true'
    name: Release image (${{ matrix.docker_image_rule }}-${{ matrix.arch }})
    runs-on: ubuntu-latest
    needs: [prepare-inputs , image_matrix_prep ]
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
        docker_image_rule: ${{ fromJson(needs.image_matrix_prep.outputs.matrix) }}
        exclude:
          # issues with building on qemu
          - arch: arm64
            docker_image_rule: handler-builder-dotnetcore-onbuild
    steps:
      - name: Prepare envs
        run: |
          echo "NUCLIO_DOCKER_REPO=${{ env.REPO }}/${{ env.REPO_NAME }}" >> $GITHUB_ENV
          echo "NUCLIO_CACHE_REPO=${{ env.CACHE_REPO }}/${{ env.CACHE_REPO_NAME }}" >> $GITHUB_ENV
          echo "NUCLIO_ARCH=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Set NUCLIO_LABEL to release tag
        run: echo "NUCLIO_LABEL=${{ needs.prepare-inputs.outputs.version }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          # checkout to the specified branch to be able to run workflow from development branch
          # and release from the specified branch
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: Install QEMU
        if: matrix.arch != 'amd64'
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # 3.6.0
        with:
          platforms: ${{ matrix.arch }}

      - name: Login to registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # 3.4.0
        with:
          registry: ${{ env.REPO }}
          username: ${{ secrets.QUAYIO_DOCKER_USERNAME }}
          password: ${{ secrets.QUAYIO_DOCKER_PASSWORD }}

      - name: Login to cache registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # 3.4.0
        with:
          registry: ${{ env.CACHE_REPO }}
          username: ${{ env.CACHE_REPO_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.docker_image_rule }} image
        run: |
          make pull-docker-images-cache || true
          make docker-images
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_IMAGES_RULES: ${{ matrix.docker_image_rule }}

          # this only applies when target is `handler-builder-golang-onbuild`
          # not applied when target is `handler-builder-golang-onbuild-alpine`
          SKIP_BUILD_GOLANG_ONBUILD_ALPINE: true

      - name: Push cache images
        if: env.NUCLIO_LABEL == 'unstable'
        run: make push-docker-images-cache
        env:
          DOCKER_IMAGES_RULES: ${{ matrix.docker_image_rule }}
          SKIP_BUILD_GOLANG_ONBUILD_ALPINE: true

      - name: Push images
        run: make push-docker-images
        env:
          DOCKER_IMAGES_RULES: ${{ matrix.docker_image_rule }}
          SKIP_BUILD_GOLANG_ONBUILD_ALPINE: true

      - name: Tag and push stable images
        if: env.NUCLIO_LABEL != 'unstable' && github.event.release.target_commitish == 'master' && contains(matrix.docker_image_rule, 'dashboard')
        run: |
          docker tag "$NUCLIO_DOCKER_REPO/dashboard:$NUCLIO_LABEL-$NUCLIO_ARCH" "$NUCLIO_DOCKER_REPO/dashboard:stable-$NUCLIO_ARCH"
          docker push "$NUCLIO_DOCKER_REPO/dashboard:stable-$NUCLIO_ARCH"
        env:
          DOCKER_IMAGES_RULES: ${{ matrix.docker_image_rule }}

  release_binary:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.bump_helm_charts_only != 'true'
    name: Release Binary ${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: [ prepare-inputs ]
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - name: Prepare envs
        run: |
          echo "NUCLIO_ARCH=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Set NUCLIO_LABEL to release tag
        run: echo "NUCLIO_LABEL=${{ needs.prepare-inputs.outputs.version }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          # checkout to the specified branch to be able to run workflow from development branch
          # and release from the specified branch
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: Install QEMU
        if: matrix.arch != 'amd64'
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # 3.6.0
        with:
          platforms: ${{ matrix.arch }}

      - name: Build binaries
        run: |
          NUCLIO_OS=linux make tools
          NUCLIO_OS=darwin make tools
          if [ $NUCLIO_ARCH == "amd64" ]; then \
            NUCLIO_OS=windows make tools; \
          fi;
        env:
          NUCLIO_NUCTL_CREATE_SYMLINK: false
          GOPATH: /home/runner/go
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}

      - name: Upload binaries
        uses: AButler/upload-release-assets@3d6774fae0ed91407dc5ae29d576b166536d1777 # v3.0
        with:
          release-tag: ${{ needs.prepare-inputs.outputs.version }}
          files: '/home/runner/go/bin/nuctl-*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  helm-publish:
    name: Publish helm charts
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.skip_bump_helm_charts != 'true' || github.event.inputs.bump_helm_charts_only == 'true')
    needs: [ prepare-inputs, release-images ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         ref: ${{ github.event.inputs.branch }}

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: nuclio-helm

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # 4.3.0

      - name: Set up yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.15.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Set commit message
        id: set_commit_message
        run: |
          HELM_PUBLISH_COMMIT_MESSAGE="Releasing chart ${{ needs.prepare-inputs.outputs.helm_version }}"
          echo "HELM_PUBLISH_COMMIT_MESSAGE=$HELM_PUBLISH_COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Create package and update index
        run: |
          echo "Creating package and updating index"
          helm package -d nuclio-helm/charts hack/k8s/helm/nuclio
          cd nuclio-helm/charts
          helm repo index . --url https://nuclio.github.io/nuclio/charts/ --merge index.yaml

      - name: Create PR to gh-pages
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "${{ env.HELM_PUBLISH_COMMIT_MESSAGE }}"
          title: "${{ env.HELM_PUBLISH_COMMIT_MESSAGE }}"
          body: |
            This PR publishes the Helm chart for version `${{ needs.prepare-inputs.outputs.helm_version }}`.

            ⚠️ Please ensure the branch `${{ github.event.inputs.branch }}` has been bumped before merging this PR.
          branch: release/helm-chart-${{ needs.prepare-inputs.outputs.helm_version }}
          base: gh-pages
          path: nuclio-helm
          delete-branch: true
