# Copyright 2017 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Security Scan

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to scan'
        required: false
        default: ''
      image_rules_override:
        description: 'Image rules override (comma separated)'
        required: false
        default: ''

env:
  NUCLIO_LABEL: latest
  NUCLIO_ARCH: amd64
  DOCKER_BUILDKIT: 1

jobs:
  matrix_prep:
    name: Prepare image list
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      # checkout from development
      - uses: actions/checkout@v3
        if: github.event.inputs.pr_number == ''

      # checkout from PR
      - uses: actions/checkout@v3
        if: github.event.inputs.pr_number != ''
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.inputs.pr_number }}/merge

      - name: Overriding image rules
        if: github.event.inputs.image_rules_override != ''
        run:
          echo "DOCKER_IMAGES_RULES=$(echo ${{ github.event.inputs.image_rules_override }} | tr ',' ' ')" >> $GITHUB_ENV

      - name: print targets
        id: set-matrix
        run: |
          docker_image_rules_json=$(make print-docker-image-rules-json)

          # if "handler-builder-golang-onbuild" is in the matrix
          # then ensure "handler-builder-golang-onbuild-alpine" is there too.
          docker_image_rules_json=$(echo $docker_image_rules_json | \
            jq -c 'select(.[].image_rule=="handler-builder-golang-onbuild") += [{"image_rule":"handler-builder-golang-onbuild-alpine"}]')
          echo "matrix={\"include\":$(echo $docker_image_rules_json)}" >> $GITHUB_OUTPUT

  build_and_scan_docker_images:
    name: Scan docker image
    runs-on: ubuntu-latest
    needs: matrix_prep
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
    steps:

      # checkout from development
      - uses: actions/checkout@v3
        if: github.event.inputs.pr_number == ''

      # checkout from PR
      - uses: actions/checkout@v3
        if: github.event.inputs.pr_number != ''
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.inputs.pr_number }}/merge

      - name: Build ${{ matrix.image_rule }} image
        run: make docker-images
        env:
          DOCKER_IMAGES_RULES: ${{ matrix.image_rule }}

      - name: Get image name for ${{ matrix.image_rule }}
        run: echo "image_name=$(make print-docker-images)" >> $GITHUB_ENV
        env:
          DOCKER_IMAGES_RULES: ${{ matrix.image_rule }}

          # for image rules that yields multiple images (e.g.: golang + golang-alpine)
          PRINT_FIRST_IMAGE: true

      - name: Define output format
        id: trivy-output-format
        run: |
          if [[ -z "${{ github.event.inputs.pr_number }}" ]]; then \
            echo "format=sarif" >> $GITHUB_OUTPUT; \
            echo "output=trivy-results.sarif" >> $GITHUB_OUTPUT; \
            echo "exit_code=0" >> $GITHUB_OUTPUT; \
          else \
            echo "format=table" >> $GITHUB_OUTPUT; \
            echo "output=" >> $GITHUB_OUTPUT; \
            echo "exit_code=1" >> $GITHUB_OUTPUT; \
          fi

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ env.image_name }}
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          ignore-unfixed: true
          output: ${{ steps.trivy-output-format.outputs.output }}
          format: ${{ steps.trivy-output-format.outputs.format }}
          exit-code: ${{ steps.trivy-output-format.outputs.exit_code }}

      - name: Upload Trivy scan results to GitHub Security tab
        # upload results if not running against pr.
        # we do not want to manipulate our security reports
        # with work-in-progress.
        if: github.event.inputs.pr_number == ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: ${{ matrix.image_rule }}

  scale_fs:
    name: Scan file system
    runs-on: ubuntu-latest
    steps:

      # checkout from development
      - uses: actions/checkout@v3
        if: github.event.inputs.pr_number == ''

      # checkout from PR
      - uses: actions/checkout@v3
        if: github.event.inputs.pr_number != ''
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.inputs.pr_number }}/merge

      - name: Define output format
        id: trivy-output-format
        run: |
          if [[ -z "${{ github.event.inputs.pr_number }}" ]]; then \
            echo "format=sarif" >> $GITHUB_OUTPUT; \
            echo "output=trivy-results.sarif" >> $GITHUB_OUTPUT; \
            echo "exit_code=0" >> $GITHUB_OUTPUT; \
          else \
            echo "format=table" >> $GITHUB_OUTPUT; \
            echo "output=" >> $GITHUB_OUTPUT; \
            echo "exit_code=1" >> $GITHUB_OUTPUT; \
          fi

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          output: ${{ steps.trivy-output-format.outputs.output }}
          format: ${{ steps.trivy-output-format.outputs.format }}
          exit-code: ${{ steps.trivy-output-format.outputs.exit_code }}

      - name: Upload Trivy scan results
        # upload results if not running against pr.
        # we do not want to manipulate our security reports
        # with work-in-progress.
        if: github.event.inputs.pr_number == ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: filesystem
