# Copyright 2017 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Security Scan


on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to scan'
        required: false
        default: ''
      upload_sarif:
        description: 'Upload SARIF (change to true to upload)'
        required: false
        default: 'false'

env:
  NUCLIO_LABEL: latest
  NUCLIO_ARCH: amd64

jobs:
  build_docker_images:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:

      # checkout from development
      - uses: actions/checkout@v3
        if: github.event.inputs.pr_number == ''

      # checkout from PR
      - uses: actions/checkout@v3
        if: github.event.inputs.pr_number != ''
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.inputs.pr_number }}/merge

      - name: Freeing up disk space
        run: |
          "${GITHUB_WORKSPACE}/hack/scripts/ci/free-space.sh"

      - name: Build
        run: make docker-images

      - name: Save
        run: make save-docker-images

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: nuclio-docker-images
          path: nuclio-docker-images-*.tar.gz

  scan_docker_images:
    name: Scan docker images
    runs-on: ubuntu-latest
    needs: build_docker_images
    steps:
      - name: Fetch nuclio docker images
        uses: actions/download-artifact@v3
        with:
          name: nuclio-docker-images

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: nuclio-docker-images-${{ env.NUCLIO_LABEL }}-${{ env.NUCLIO_ARCH }}.tar.gz
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          ignore-unfixed: true
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: github.event.inputs.upload_sarif != 'false'
        with:
          sarif_file: 'trivy-results.sarif'
